[package]
name = "cilens"
repository = "https://github.com/dsalaza4/cilens"
version = "0.7.1"
edition = "2021"
authors = ["Daniel Salazar <podany270895@gmail.com>"]
description = "A CLI tool for collecting and analyzing CI/CD insights"
license = "MIT"
keywords = ["ci-cd", "gitlab", "devops", "analytics", "cli", "pipelines"]
categories = ["command-line-utilities", "development-tools"]
homepage = "https://github.com/dsalaza4/cilens"
documentation = "https://github.com/dsalaza4/cilens"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive", "env"] }
comfy-table = "7.1"
console = "0.15"
dirs = "5.0"
env_logger = "0.11"
futures = "0.3.31"
graphql_client = "0.14"
indexmap = { version = "2", features = ["serde"] }
indicatif = "0.17"
log = "0.4"
reqwest = { version = "0.12", features = [
  "json",
  "rustls-tls",
], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.40", features = ["full"] }
url = "2.5"

[dev-dependencies]
mockito = "1.5"
tempfile = "3.13"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
codegen-units = 1
lto = "fat"
